const GET_STATE_DATA_ASYNC = 'GET_STATE_DATA_ASYNC';
const GET_STATE_DATA_ERROR = 'GET_STATE_DATA_ERROR';
const GET_STATE_DATA_INIT = 'GET_STATE_DATA_INIT';
const GET_STATE_DATA_SUCCESS = 'GET_STATE_DATA_SUCCESS';
const UPDATE_COLUMN_SORT = 'UPDATE_COLUMN_SORT';

export {
  GET_STATE_DATA_ASYNC,
  GET_STATE_DATA_ERROR,
  GET_STATE_DATA_INIT,
  GET_STATE_DATA_SUCCESS,
  UPDATE_COLUMN_SORT,
};
