const GET_STATE_DATA = 'GET_STATE_DATA';
const GET_STATE_DATA_ASYNC = 'GET_STATE_DATA_ASYNC';
const UPDATE_COLUMN_SORT = 'UPDATE_COLUMN_SORT';

export { GET_STATE_DATA, GET_STATE_DATA_ASYNC, UPDATE_COLUMN_SORT };
